[package]
name = "database"
version = "0.1.0"
edition = "2021"


[lib]
name = "db"
path = "src/lib.rs"

[dependencies]
syn = "1.0"
quote = "1.0"
leveldb = "0.8.6"
tempdir = "0.3.7"
serde = "1.0.143"
serde_json = "1.0"